# -*- coding: utf-8 -*-
"""Sign_Language_Classification_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfxnsiIhkoJXUo0skspEVWQuVL9Y0UAu
"""

import random
import numpy as np
import torch

seed = 42

random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)


torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

!pip install gdown

import gdown

file_id = "1aWYbQhayjmA6J2sHrQzyld76_yTSg3tn"
url = f"https://drive.google.com/uc?id={file_id}"

output = "asl.zip"
gdown.download(url, output, quiet=False)

import zipfile

with zipfile.ZipFile("asl.zip", 'r') as zip_ref:
    zip_ref.extractall("asl_data")

import os
os.listdir("asl_data/SignAlphaSet")

root_dir = "asl_data/SignAlphaSet"
print(root_dir)

# Giving a numerical label to each file

import os

classes = sorted(os.listdir(root_dir))
class_to_idx = {cls_name: i for i, cls_name in enumerate(classes)}

print("Classes:", classes)
print("Mapping:", class_to_idx)

import os
from PIL import Image
import numpy as np

# pick first class
first_class = classes[0]

# path to that folder
class_path = os.path.join(root_dir, first_class)

# pick one image
img_name = os.listdir(class_path)[0]
img_path = os.path.join(class_path, img_name)

print("Class:", first_class)
print("Image path:", img_path)

# read image
image = Image.open(img_path).convert("RGB")

# convert to numpy
image_np = np.array(image)

print("Shape:", image_np.shape)

import torch

# convert numpy to tensor
image_tensor = torch.from_numpy(image_np)

# change (H,W,C) -> (C,H,W)
image_tensor = image_tensor.permute(2, 0, 1)

# convert to float and normalize pixel values (0-255 -> 0-1)
image_tensor = image_tensor.float() / 255.0

print("Tensor shape:", image_tensor.shape)
print("Tensor dtype:", image_tensor.dtype)

from torch.utils.data import Dataset
from PIL import Image
import numpy as np
import os
import torch

class ASLDataset(Dataset):

    # initialization: store paths and mapping
    def __init__(self, root_dir, class_to_idx):
        self.root_dir = root_dir
        self.class_to_idx = class_to_idx

        # collecting all image paths and their labels
        self.samples = []
        for class_name in sorted(os.listdir(root_dir)):
            class_path = os.path.join(root_dir, class_name)

            for img_name in sorted(os.listdir(class_path)):
                img_path = os.path.join(class_path, img_name)
                label = self.class_to_idx[class_name]
                self.samples.append((img_path, label))

    # total number of images
    def __len__(self):
        return len(self.samples)

    # how to read one image
    def __getitem__(self, idx):
        img_path, label = self.samples[idx]

        # reading image
        image = Image.open(img_path).convert("RGB")
        image = np.array(image)

        # numpy -> tensor + rearrange + normalize
        image = torch.from_numpy(image).permute(2,0,1).float()/255.0

        return image, label

dataset = ASLDataset(root_dir, class_to_idx)

print("Total images:", len(dataset))

image, label = dataset[0]

print("Image shape:", image.shape)
print("Label:", label)
print("Label type:", type(label))

from torch.utils.data import random_split

generator = torch.Generator().manual_seed(seed)

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(
    dataset,
    [train_size, val_size],
    generator=generator
)

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))

from torch.utils.data import DataLoader

batch_size = 32

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

print("Dataloaders ready")

images, labels = next(iter(train_loader))

print("Train batch shape:", images.shape)
print("Labels shape:", labels.shape)

import torch
import torch.nn as nn


class CNN(nn.Module):

    def __init__(self):
        super().__init__()


        self.features = nn.Sequential(

            # Block 1
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.Conv2d(32, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2),

            # Block 2
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2),

            # Block 3
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )

        # Global average pooling layer
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Classification head
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(128, 26)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.global_pool(x)
        x = self.classifier(x)
        return x

device="cuda" if torch.cuda.is_available() else "cpu"
model = CNN().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

import torch



model = model.to(device)


criterion = torch.nn.CrossEntropyLoss()


optimizer = torch.optim.Adam(model.parameters(), lr=0.0005)

print("Using device:", device)

epochs = 7
best_val_acc = 0.0

for epoch in range(epochs):

    # -------- Training Phase --------
    model.train()
    train_loss = 0.0
    train_correct = 0
    train_total = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        # Forward propagation
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backpropagation and parameter update
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Accumulate loss
        train_loss += loss.item()

        # Compute training accuracy
        preds = torch.argmax(outputs, dim=1)
        train_correct += (preds == labels).sum().item()
        train_total += labels.size(0)

    avg_train_loss = train_loss / len(train_loader)
    train_accuracy = train_correct / train_total


    # -------- Validation Phase --------
    model.eval()
    val_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for images, labels in val_loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)
            val_correct += (preds == labels).sum().item()
            val_total += labels.size(0)

    avg_val_loss = val_loss / len(val_loader)
    val_accuracy = val_correct / val_total

    if val_accuracy > best_val_acc:
       best_val_acc = val_accuracy
       torch.save(model.state_dict(), "model_cnn.pth")


    # -------- Epoch Summary --------
    print(
        f"Epoch [{epoch+1}/{epochs}] | "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Train Acc: {train_accuracy:.4f} | "
        f"Val Loss: {avg_val_loss:.4f} | "
        f"Val Acc: {val_accuracy:.4f}"
    )

from google.colab import files
files.download("model_cnn.pth")

import torch

weights = torch.load("model_cnn.pth", map_location="cpu")

print(weights.keys())