# -*- coding: utf-8 -*-
"""Temporal_Sequence_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmW5Zb9jv_0K9Cf2p_LSCjtqpdLdVv6_
"""

import random
import numpy as np
import torch

seed = 42

random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)


torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

import gdown

file_id = "1IkabBeuutdjTo4Mjjm1eMfTUujWjiIJA"
url = f"https://drive.google.com/uc?id={file_id}"

output = "asl.zip"
gdown.download(url, output, quiet=False)

import zipfile

with zipfile.ZipFile("asl.zip", 'r') as zip_ref:
    zip_ref.extractall("asl_data")

# -------------------------------
# Dataset root configuration
# -------------------------------

import os

# Root directory containing all gesture classes
root_dir = "asl_data/ASL_dynamic"


# -------------------------------
# Class discovery and indexing
# -------------------------------

# Retrieve class names from directory structure
classes = sorted([
    d for d in os.listdir(root_dir)
    if os.path.isdir(os.path.join(root_dir, d))
])

# Create mapping from class name to numeric label
class_to_idx = {class_name: idx for idx, class_name in enumerate(classes)}

# Display dataset summary
print("Number of classes:", len(classes))
print("Classes:", classes)
print("Class mapping:", class_to_idx)

# -------------------------------
# Sequence Dataset for ASL clips
# -------------------------------

from torch.utils.data import Dataset
from PIL import Image
import torch
import numpy as np

class ASLDynamicDataset(Dataset):

    def __init__(self, root_dir, class_to_idx, seq_len=16, img_size=224):
        self.root_dir = root_dir
        self.class_to_idx = class_to_idx
        self.seq_len = seq_len
        self.img_size = img_size
        self.samples = []
        self.aug_factor = 5

        # Collect all clip frame folders
        for class_name in class_to_idx.keys():

            class_path = os.path.join(root_dir, class_name)

            for item in os.listdir(class_path):
                if item.endswith("_frames"):

                    clip_path = os.path.join(class_path, item)
                    label = class_to_idx[class_name]

                    self.samples.append((clip_path, label))

    def __len__(self):
        return len(self.samples)*self.aug_factor

    def __getitem__(self, idx):

        clip_path, label = self.samples[idx % len(self.samples)]

        frame_files = sorted([
            f for f in os.listdir(clip_path)
            if f.endswith(".jpg")
        ])

        # Uniformly sample 16 frames
        if len(frame_files) >= self.seq_len:
           start = np.random.randint(0, len(frame_files) - self.seq_len + 1)
           indices = np.arange(start, start + self.seq_len)
        else:
           indices = np.linspace(
           0,
           len(frame_files) - 1,
           self.seq_len,
           dtype=int
         )

        frames = []

        for i in indices:
            img_path = os.path.join(clip_path, frame_files[i])


            image = Image.open(img_path).convert("RGB")
            image = np.array(image)

            h, w, _ = image.shape

            # crop upper-center region (focus on hands)
            h, w, _ = image.shape

            top = np.random.randint(0, int(0.3*h))
            left = np.random.randint(0, int(0.3*w))

            image = image[
            top:top+int(0.6*h),
            left:left+int(0.6*w)
            ]
            # resize after cropping
            image = Image.fromarray(image).resize((self.img_size, self.img_size))
            image = np.array(image)
            image = torch.from_numpy(image).permute(2,0,1).float()/255.0

            # ---- brightness augmentation ----
            if random.random() < 0.5:
               image = image * (0.8 + 0.4 * random.random())
               image = torch.clamp(image, 0, 1)

           # ---- horizontal flip ----
            if random.random() < 0.5:
               image = torch.flip(image, dims=[2])

           # ---- normalization ----
            mean = torch.tensor([0.485, 0.456, 0.406]).view(3,1,1)
            std = torch.tensor([0.229, 0.224, 0.225]).view(3,1,1)

            image = (image - mean) / std

            frames.append(image)

        frames = torch.stack(frames)

        return frames, label

dataset = ASLDynamicDataset(root_dir, class_to_idx)

frames, label = dataset[0]

print("Frames shape:", frames.shape)
print("Label:", label)

# -------------------------------
# Dataset split and dataloaders
# -------------------------------

from torch.utils.data import random_split, DataLoader

# Train / validation split
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

print("Train samples:", len(train_dataset))
print("Validation samples:", len(val_dataset))


# DataLoader configuration
batch_size = 4

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False
)


# Verify batch shape
frames, labels = next(iter(train_loader))

print("Batch frames shape:", frames.shape)
print("Batch labels shape:", labels.shape)

# ---------------------------------------
# CNN architecture definition
# ---------------------------------------

import torch
import torch.nn as nn

class CNN(nn.Module):

    def __init__(self):
        super().__init__()

        self.features = nn.Sequential(

            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),

            nn.Conv2d(32, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),

            nn.Conv2d(64, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),

            nn.Conv2d(128, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.global_pool = nn.AdaptiveAvgPool2d((1,1))

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128,128),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(128,31)
        )

    def forward(self, x):

        x = self.features(x)
        x = self.global_pool(x)
        x = self.classifier(x)

        return x

import gdown

file_id = "1U10XyTt3Lluz7oziPvMWRRRlFzz0atnk"
url = f"https://drive.google.com/uc?id={file_id}"

output = "model_cnn.pth"
gdown.download(url, output, quiet=False)

# ---------------------------------------
# Initialize CNN backbone
# ---------------------------------------

cnn_backbone = CNN()


# ---------------------------------------
# Remove classifier before loading weights
# ---------------------------------------

cnn_backbone.classifier = torch.nn.Identity()


# ---------------------------------------
# Load pretrained weights
# ---------------------------------------

state_dict = torch.load("model_cnn.pth", map_location="cpu")

cnn_backbone.load_state_dict(state_dict, strict=False)


# ---------------------------------------
# Freeze CNN parameters
# ---------------------------------------

for param in cnn_backbone.parameters():
    param.requires_grad = False



print("CNN backbone ready.")

dummy = torch.randn(1,3,224,224)

with torch.no_grad():
    features = cnn_backbone(dummy)

print(features.shape)

# ---------------------------------------
# CNN + LSTM architecture
# ---------------------------------------

import torch.nn as nn

class CNN_LSTM_Model(nn.Module):

    def __init__(self, cnn_backbone, num_classes):

        super().__init__()

        self.cnn = cnn_backbone

        # Projection layer to match assignment requirement
        self.feature_proj = nn.Linear(128, 512)

        # Temporal modeling
        self.lstm = nn.LSTM(
            input_size=512,
            hidden_size=512,
            num_layers=2,
            batch_first=True
        )

        # Classification head
        self.classifier = nn.Sequential(
            nn.Linear(512,128),
            nn.ReLU(),
            nn.Linear(128,num_classes)
        )

    def forward(self, x):

     B, T, C, H, W = x.shape

     # Merge batch and time dimension
     x = x.view(B*T, C, H, W)

     # Extract spatial features
     features = self.cnn(x)           # (B*T,128,1,1)

     features = features.view(B*T, 128)

     # Project to 512-dim
     features = self.feature_proj(features)

     # Restore temporal dimension
     features = features.view(B, T, 512)

     # LSTM temporal modeling
     lstm_out, _ = self.lstm(features)

     # Final timestep representation
     final_feature = torch.mean(lstm_out, dim=1)

     output = self.classifier(final_feature)

     return output

num_classes = len(classes)

model = CNN_LSTM_Model(cnn_backbone, num_classes)

print("Model initialized.")

dummy = torch.randn(2,16,3,224,224)

out = model(dummy)

print(out.shape)

# ---------------------------------------
# Device configuration
# ---------------------------------------

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = model.to(device)

print("Using device:", device)

# ---------------------------------------
# Loss function
# ---------------------------------------

criterion = torch.nn.CrossEntropyLoss(label_smoothing=0.1)

# ---------------------------------------
# Optimizer
# ---------------------------------------

# Only train parameters that require gradients
trainable_params = filter(lambda p: p.requires_grad, model.parameters())

optimizer = torch.optim.AdamW(
    trainable_params,
    lr=0.0003,
    weight_decay=0.01
)
epochs=32
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=epochs
)

trainable_count = sum(p.numel() for p in model.parameters() if p.requires_grad)

print("Trainable parameters:", trainable_count)

# ---------------------------------------
# Training loop
# ---------------------------------------

epochs = 28
best_val_acc = 0

for epoch in range(epochs):

    # ----- Training phase -----
    model.train()

    train_loss = 0
    train_correct = 0
    train_total = 0

    for frames, labels in train_loader:

        frames = frames.to(device)
        labels = labels.to(device)

        outputs = model(frames)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        train_loss += loss.item()

        preds = torch.argmax(outputs, dim=1)

        train_correct += (preds == labels).sum().item()
        train_total += labels.size(0)

    avg_train_loss = train_loss / len(train_loader)
    train_acc = train_correct / train_total


    # ----- Validation phase -----
    model.eval()

    val_loss = 0
    val_correct = 0
    val_total = 0

    with torch.no_grad():

        for frames, labels in val_loader:

            frames = frames.to(device)
            labels = labels.to(device)

            outputs = model(frames)

            loss = criterion(outputs, labels)

            val_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)

            val_correct += (preds == labels).sum().item()
            val_total += labels.size(0)

    avg_val_loss = val_loss / len(val_loader)
    val_acc = val_correct / val_total


    # ----- Save best model -----
    if val_acc > best_val_acc:

        best_val_acc = val_acc
        torch.save(model.state_dict(), "cnn_lstm_best.pth")


    # ----- Epoch summary -----
    print(
        f"Epoch [{epoch+1}/{epochs}] | "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Train Acc: {train_acc:.4f} | "
        f"Val Loss: {avg_val_loss:.4f} | "
        f"Val Acc: {val_acc:.4f}"
    )

    scheduler.step()

from google.colab import files
files.download("cnn_lstm_best.pth")

model.load_state_dict(torch.load("cnn_lstm_best.pth"))
model.eval()